#!/bin/bash

# Define your list of test names
test_names=(
    # # Floating-point conversion instructions (SEW=32, all LMULs)
#    "VFCVT-F-XU-V-SEW32_LMUL1"      "VFCVT-F-XU-V-SEW32_LMUL2"     "VFCVT-F-XU-V-SEW32_LMUL4"     "VFCVT-F-XU-V-SEW32_LMUL8"
    # "VFCVT-F-X-V-SEW32_LMUL1"      "VFCVT-F-X-V-SEW32_LMUL2"      "VFCVT-F-X-V-SEW32_LMUL4"      "VFCVT-F-X-V-SEW32_LMUL8"
    # "VFCVT-XU-F-V-SEW32_LMUL1"     "VFCVT-XU-F-V-SEW32_LMUL2"     "VFCVT-XU-F-V-SEW32_LMUL4"     "VFCVT-XU-F-V-SEW32_LMUL8"
    # "VFCVT-X-F-V-SEW32_LMUL1"      "VFCVT-X-F-V-SEW32_LMUL2"      "VFCVT-X-F-V-SEW32_LMUL4"      "VFCVT-X-F-V-SEW32_LMUL8"
    # "VFCVT-RTZ-XU-F-V-SEW32_LMUL1" "VFCVT-RTZ-XU-F-V-SEW32_LMUL2" "VFCVT-RTZ-XU-F-V-SEW32_LMUL4" "VFCVT-RTZ-XU-F-V-SEW32_LMUL8"
    # "VFCVT-RTZ-X-F-V-SEW32_LMUL1"  "VFCVT-RTZ-X-F-V-SEW32_LMUL2"  "VFCVT-RTZ-X-F-V-SEW32_LMUL4"  "VFCVT-RTZ-X-F-V-SEW32_LMUL8"

    # # Vector Single-Width Floating-Point Add/Subtract Instructions (SEW=32, all LMULs)
    # "VFADD-VV-SEW32_LMUL1"  "VFADD-VV-SEW32_LMUL2"  "VFADD-VV-SEW32_LMUL4"  "VFADD-VV-SEW32_LMUL8"
    # "VFADD-VF-SEW32_LMUL1"  "VFADD-VF-SEW32_LMUL2"  "VFADD-VF-SEW32_LMUL4"  "VFADD-VF-SEW32_LMUL8"
    # "VFSUB-VV-SEW32_LMUL1"  "VFSUB-VV-SEW32_LMUL2"  "VFSUB-VV-SEW32_LMUL4"  "VFSUB-VV-SEW32_LMUL8"
    # "VFSUB-VF-SEW32_LMUL1"  "VFSUB-VF-SEW32_LMUL2"  "VFSUB-VF-SEW32_LMUL4"  "VFSUB-VF-SEW32_LMUL8"
    # "VFRSUB-VF-SEW32_LMUL1" "VFRSUB-VF-SEW32_LMUL2" "VFRSUB-VF-SEW32_LMUL4" "VFRSUB-VF-SEW32_LMUL8"

    # Vector Floating-Point Multiply Instructions (SEW=32, all LMULs)
    # "VFMUL-VV-SEW32_LMUL1" "VFMUL-VV-SEW32_LMUL2" "VFMUL-VV-SEW32_LMUL4" "VFMUL-VV-SEW32_LMUL8"
    # "VFMUL-VF-SEW32_LMUL1" "VFMUL-VF-SEW32_LMUL2" "VFMUL-VF-SEW32_LMUL4" "VFMUL-VF-SEW32_LMUL8"

    # # Floating-Point Minimum/Maximum (SEW=32, all LMULs)
    # "VFMIN-VV-SEW32_LMUL1" "VFMIN-VV-SEW32_LMUL2" "VFMIN-VV-SEW32_LMUL4" "VFMIN-VV-SEW32_LMUL8"
    # "VFMIN-VF-SEW32_LMUL1" "VFMIN-VF-SEW32_LMUL2" "VFMIN-VF-SEW32_LMUL4" "VFMIN-VF-SEW32_LMUL8"
    # "VFMAX-VV-SEW32_LMUL1" "VFMAX-VV-SEW32_LMUL2" "VFMAX-VV-SEW32_LMUL4" "VFMAX-VV-SEW32_LMUL8"
    # "VFMAX-VF-SEW32_LMUL1" "VFMAX-VF-SEW32_LMUL2" "VFMAX-VF-SEW32_LMUL4" "VFMAX-VF-SEW32_LMUL8"

    # # Fused Multiply-Add Instructions (SEW=32, all LMULs)
    # "VFMACC-VV-SEW32_LMUL1" "VFMACC-VV-SEW32_LMUL2" "VFMACC-VV-SEW32_LMUL4" "VFMACC-VV-SEW32_LMUL8"
    # "VFMACC-VF-SEW32_LMUL1" "VFMACC-VF-SEW32_LMUL2" "VFMACC-VF-SEW32_LMUL4" "VFMACC-VF-SEW32_LMUL8"
    # "VFNMACC-VV-SEW32_LMUL1" "VFNMACC-VV-SEW32_LMUL2" "VFNMACC-VV-SEW32_LMUL4" "VFNMACC-VV-SEW32_LMUL8"
    # "VFNMACC-VF-SEW32_LMUL1" "VFNMACC-VF-SEW32_LMUL2" "VFNMACC-VF-SEW32_LMUL4" "VFNMACC-VF-SEW32_LMUL8"
    # "VFMSAC-VV-SEW32_LMUL1" "VFMSAC-VV-SEW32_LMUL2" "VFMSAC-VV-SEW32_LMUL4" "VFMSAC-VV-SEW32_LMUL8"
    # "VFMSAC-VF-SEW32_LMUL1" "VFMSAC-VF-SEW32_LMUL2" "VFMSAC-VF-SEW32_LMUL4" "VFMSAC-VF-SEW32_LMUL8"
    # "VFNMSAC-VV-SEW32_LMUL1" "VFNMSAC-VV-SEW32_LMUL2" "VFNMSAC-VV-SEW32_LMUL4" "VFNMSAC-VV-SEW32_LMUL8"
    # "VFNMSAC-VF-SEW32_LMUL1" "VFNMSAC-VF-SEW32_LMUL2" "VFNMSAC-VF-SEW32_LMUL4" "VFNMSAC-VF-SEW32_LMUL8"
    # "VFMADD-VV-SEW32_LMUL1" "VFMADD-VV-SEW32_LMUL2" "VFMADD-VV-SEW32_LMUL4" "VFMADD-VV-SEW32_LMUL8"
    # "VFMADD-VF-SEW32_LMUL1" "VFMADD-VF-SEW32_LMUL2" "VFMADD-VF-SEW32_LMUL4" "VFMADD-VF-SEW32_LMUL8"
    # "VFNMADD-VV-SEW32_LMUL1" "VFNMADD-VV-SEW32_LMUL2" "VFNMADD-VV-SEW32_LMUL4" "VFNMADD-VV-SEW32_LMUL8"
    # "VFNMADD-VF-SEW32_LMUL1" "VFNMADD-VF-SEW32_LMUL2" "VFNMADD-VF-SEW32_LMUL4" "VFNMADD-VF-SEW32_LMUL8"
    # "VFMSUB-VV-SEW32_LMUL1" "VFMSUB-VV-SEW32_LMUL2" "VFMSUB-VV-SEW32_LMUL4" "VFMSUB-VV-SEW32_LMUL8"
    # "VFMSUB-VF-SEW32_LMUL1" "VFMSUB-VF-SEW32_LMUL2" "VFMSUB-VF-SEW32_LMUL4" "VFMSUB-VF-SEW32_LMUL8"
    # "VFNMSUB-VV-SEW32_LMUL1" "VFNMSUB-VV-SEW32_LMUL2" "VFNMSUB-VV-SEW32_LMUL4" "VFNMSUB-VV-SEW32_LMUL8"
    # "VFNMSUB-VF-SEW32_LMUL1" "VFNMSUB-VF-SEW32_LMUL2" "VFNMSUB-VF-SEW32_LMUL4" "VFNMSUB-VF-SEW32_LMUL8"

    # "VFDIV-VV-SEW32_LMUL1"  "VFDIV-VV-SEW32_LMUL2"   "VFDIV-VV-SEW32_LMUL4"   "VFDIV-VV-SEW32_LMUL8"
    # "VFDIV-VF-SEW32_LMUL1"  "VFDIV-VF-SEW32_LMUL2"   "VFDIV-VF-SEW32_LMUL4"   "VFDIV-VF-SEW32_LMUL8"
    # "VFRDIV-VF-SEW32_LMUL1"  "VFRDIV-VF-SEW32_LMUL2"   "VFRDIV-VF-SEW32_LMUL4"   "VFRDIV-VF-SEW32_LMUL8"

)

# Set your device and ISA parameters
DEVICE="Vf"   # Example: 'v' for vector tests, change this if needed
ISA="rv32i_m"  # Example ISA, adjust according to your setup

# Loop through each test in the list
for TEST in "${test_names[@]}"; do
    echo "Running compliance test for: $TEST"

    # Correct parameter sequence for the run_compliance script
    ./run_compliance.sh "$ISA" "$TEST" "$DEVICE" riscv32-unknown-elf-

    # Check if the previous command ran successfully
    if [ $? -eq 0 ]; then
        echo "Test $TEST completed successfully."
    else
        echo "Test $TEST failed."
        exit 1  # Exit the loop if any test fails
    fi
done

echo "All tests completed."